### PR TITLE
Add English RSS feed

### PR DESCRIPTION
**Pull request by fexfexfex**
Needs testing, I manage compiling but not running Calypso with these changes. Unsure of what is going wrong.

### CODE REVIEW

**Comment by fexfexfex** [comment]
PS C:\Users\Fex\git\calypso> mvn spring-boot:run
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< se.datasektionen:calypso >----------------------
[INFO] Building calypso 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.5.7.RELEASE:run (default-cli) > test-compile @ calypso >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ calypso ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 8 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ calypso ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 38 source files to C:\Users\Fex\git\calypso\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ calypso ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Fex\git\calypso\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ calypso ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< spring-boot-maven-plugin:1.5.7.RELEASE:run (default-cli) < test-compile @ calypso <<<
[INFO]
[INFO]
[INFO] --- spring-boot-maven-plugin:1.5.7.RELEASE:run (default-cli) @ calypso ---
[INFO] Attaching agents: []
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:93)
        at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:56)
        at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:140)
        at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:546)
        at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartingEvent(RestartApplicationListener.java:67)
        at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
        at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
        at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:292)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at se.datasektionen.calypso.Application.main(Application.java:10)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.733 s
[INFO] Finished at: 2020-10-06T12:17:11+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.7.RELEASE:run (default-cli) on project calypso: Could not exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by fexfexfex** [comment]
Vore nice om nån som lyckas bygga Calypso tittade på den här, typ @DokID eller @macfeaster. Med @oskstr kom vi fram till att det antagligen beror på en mismatch i Java-version.

**Comment by bullfest** [comment]
Klassiska alternativet när man har en dålig byggdag är att pusha till prod, se om det funkar och annars göra en rollback 😉

**Comment by oskstr** [comment]
Ja, det stämmer, jag läste någonstans att Spring Boot < v.2.0 behövde Java 8 eller tidigare. Jag testade att bara öka versionsnumret till en nyare spring version men får för mig att det var någon annan dependency som klagade på det. Men det är ju inte omöjligt att köra med `jenv` eller nåt för Java 8. Mauritz har nog dock bättre koll än mig.

**Comment by macfeaster** [comment]
@oskstr har rätt. Kör antingen med jdk8 eller kolla Boot 2.0 migration guide.

**Comment by macfeaster** [comment]
Gällande själva PR:en så kollade jag på det när jag såg din GitHub issue och min originalkod är ganska dåligt byggd – `RssComponent` borde förstås inte diktera själv vilken content den får utan bara presentera. Nu blir det väldigt copypasta pga min bristfälliga originaldesign 🙂

**Comment by oskstr** [comment]
@macfeaster , ja, du har nog rätt. Jag kanske får tid att kolla på det nån gång. Jobbade med Spring en del i somras så jag har nog lite koll iaf.

**Comment by macfeaster** [comment]
@bullfest var 100 år sen jag rörde något nu, var specar man JDK-version? Är det fortfarande typ Dokku eller något med någon spin-off Heroku buildpack? Hur byter jag? Eller kan jag göra en container och k8s chart?

**Comment by oskstr** [comment]
Jag är btw inte helt 100 på att det var JDK-versionen som var felet men jag läste det någonstans. Jag är rätt säker på att det sköts automagiskt i Dokku atm. Men det är specat längst ner i `pom.xml` att compiler ska vara `1.8`.

Det har diskuterats om att annan containerization skulle hjälpa med stabilitet, det skulle ju också göra det trivialt att bygga lokalt i samma miljö som körs i prod. Om @DokID har tid att fixa med AWS och någon vill speca containern kanske det här projektet vore något man skulle kunna testa att flytta.

**Comment by macfeaster** [comment]
Om ni testkörde på >8 så ja 🙂  Boot 1.5 är gammalt
Om det fortfarande är Dokku så gör den ju en container i slutändan, men har inte koll på vad som hänt senaste åren

**Comment by oskstr** [comment]
Det har ju varit lite problem att saker har uppdateras på något sätt och gjort att vissa system dött utan att någon rört dem. Vet inte exakt varför men det borde ju Plutten och Gabbe vara väl bekanta med skulle jag tro.

**Review by DokID — APPROVED** [review]
Aldrig använt Spring men det ser säkert jättebra ut, finns iaf inget jätteknasigt vad jag kan se.

**Comment by DokID** [comment]
Den är live 🎉

**Comment by fexfexfex** [comment]
Tack, det funkar! Nu blir både Martin Monperrus och alla internationella studenter glada 🎉😊

**Pull request merged**
