### PR TITLE
feat: support recurring events through Activities

### PR DESCRIPTION
**Pull request by RafDevX**

### CODE REVIEW

**Comment by RafDevX** [comment]
Please test extensively, and specifically see if this uses valid Swedish

**Comment by RafDevX** [comment]
Also: would appreciate ideas on how to fix the CSS around the radio buttons to make them vertically centered with their labels, but I don't understand how to style ::before pseudo-elements

**Comment by RafDevX** [comment]
@mathiasmagnusson :grinning:

**Comment by mathiasmagnusson** [comment]
> Also: would appreciate ideas on how to fix the CSS around the radio buttons to make them vertically centered with their labels, but I don't understand how to style ::before pseudo-elements

Was also not able to fix this.

**Review by mathiasmagnusson — APPROVED** [review]
Merge and purge?

**Review by mathiasmagnusson — APPROVED** [review]
Very nice!

**Pull request merged**
